// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/main/News/dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Login: typeof import('./src/components/login/index.vue')['default']
    LoginAccount: typeof import('./src/components/login/login-account.vue')['default']
    LoginPannel: typeof import('./src/components/login/login-pannel.vue')['default']
    LoginPhone: typeof import('./src/components/login/login-phone.vue')['default']
    Logo: typeof import('./src/components/nav-header/src/logo.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/src/nav-header.vue')['default']
    NavSubmenu: typeof import('./src/components/nav-header/src/nav-submenu.vue')['default']
    News: typeof import('./src/components/main/News/index.vue')['default']
    NewsResult: typeof import('./src/components/main/News/NewsResult.vue')['default']
    Order: typeof import('./src/components/order/index.vue')['default']
    Posters: typeof import('./src/components/main/News/posters.vue')['default']
    Product: typeof import('./src/components/main/product/index.vue')['default']
    ProductList: typeof import('./src/components/main/product/ProductList.vue')['default']
    ProductPoster: typeof import('./src/components/main/product/productPoster.vue')['default']
    Search: typeof import('./src/components/main/News/search.vue')['default']
    Test: typeof import('./src/components/main/product/test.vue')['default']
    UserNav: typeof import('./src/components/nav-header/src/user-nav.vue')['default']
  }
}

export { }
